---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: smoke-default
    run_list:
      - recipe[kubernetes-stack-test::default]
    verifier:
      inspec_tests:
        - test/smoke/default

  - name: smoke-kubectl
    run_list:
      - recipe[kubernetes-stack-test::kubectl_install_default]
    verifier:
      inspec_tests:
        - test/smoke/kubectl/kubectl_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true

  - name: smoke-kubectl-specific-version
    run_list:
      - recipe[kubernetes-stack-test::kubectl_install_specific_version]
    verifier:
      inspec_tests:
        - test/smoke/kubectl/kubectl_specific_version_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true

  - name: smoke-gcloud
    run_list:
      - recipe[kubernetes-stack-test::gcloud_install_default]
    verifier:
      inspec_tests:
        - test/smoke/gcloud
    attributes:
      kubernetes-stack:
        gcloud:
          enabled: true
    excludes:
      - centos-7.3
